<?php
$user=$_POST['user'];
$pass=$_POST['pass'];
if( $user=='guest' || $user=='admin')
{
    if($pass=="123")
    {
    header("location:question.php");
    }
    else
{
    header("location:A&K.php");
}
}
else
{
    header("location:A&K.php");
} 
?>